import TextLintTester from 'textlint-tester';
import rule from '../src/index';

const tester = new TextLintTester();

tester.run('ja-space-around-phrase', rule, {
  valid: [
    // === Single word without space (correct) ===
    'これはtestです',
    '日本語wordテスト',
    'あいうabc漢字',
    'テストword確認',
    '漢字abc平仮名',
    'カタカナxyz日本語',
    '文字列abc123テスト',
    'あaい',
    '漢x字',
    'カaタ',
    '日本語test日本語',
    'ひらがなword漢字',
    'カタカナabc平仮名',
    '混合test文字',
    '確認word完了',
    '開始abc終了',
    '前word後',
    '上abc下',
    '左xyz右',
    '内test外',

    // === Numbers without space (correct) ===
    'これは123です',
    '数字456テスト',
    '値789確認',
    'カウント100完了',
    '番号001登録',
    'ID999取得',
    'コード123456設定',
    '年2024月',
    '第1回',
    '全10件',
    'あ1い',
    '漢2字',
    'カ3タ',
    '数0値',
    '件100数',

    // === Phrase with space (correct) ===
    'これは hello world です',
    '日本語 foo bar テスト',
    'あいう abc def 漢字',
    'テスト hello world 確認',
    '漢字 foo bar 平仮名',
    'カタカナ abc xyz 日本語',
    '文字列 test case テスト',
    '開始 start end 終了',
    '前 before after 後',
    '上 top bottom 下',
    '左 left right 右',
    '内 inner outer 外',
    '日本語 hello world test 日本語',
    'ひらがな foo bar baz 漢字',
    'カタカナ abc def ghi 平仮名',
    '混合 test case example 文字',
    '確認 check verify 完了',
    '開始 begin start 終了',
    '設定 config setting 完了',
    '処理 process handle 終了',

    // === URL with space (correct) ===
    '詳細は https://example.com を参照',
    'サイト https://example.com/path です',
    'リンク https://example.com/path?query=1 を見て',
    '参照 https://test.org/page 確認',
    'アクセス https://sample.net/api してください',
    'ドキュメント https://docs.example.com/guide を読んで',
    'ソース https://github.com/user/repo を確認',
    'ダウンロード https://cdn.example.com/file.zip から取得',
    '情報 https://info.example.com/news を参照',
    'ヘルプ https://help.example.com/faq を見て',
    '公式 https://official.example.com です',
    'ブログ https://blog.example.com/post を読んで',
    'フォーラム https://forum.example.com/thread を確認',
    'ウィキ https://wiki.example.com/page を参照',
    'ストア https://store.example.com/item を見て',
    '詳細は http://example.com を参照',
    'ファイル ftp://files.example.com/data を取得',
    'リポジトリ git://github.com/user/repo を確認',
    'プロトコル file:///path/to/file を参照',
    'カスタム custom://app/path を使用',

    // === Email with space (correct) ===
    'メアドは foo@example.com です',
    '連絡先 test@example.co.jp まで',
    '問い合わせ info@sample.org へ',
    'サポート support@help.net まで',
    '担当者 admin@company.com に連絡',
    '送信先 mail@domain.io です',
    '返信 reply@service.com まで',
    '登録 register@site.net へ',
    '通知 notify@alert.org に設定',
    '確認 confirm@verify.com まで',
    'アドレス user123@example.com です',
    'メール contact.us@example.com へ',
    '宛先 sales-team@company.co.jp まで',
    '送付先 info_desk@support.net です',
    '連絡 help.center@service.org へ',

    // === Markdown link without space (correct) ===
    'これは[リンク](https://example.com)です',
    '詳細は[こちら](https://example.com/path)を参照',
    '[テスト](https://example.com)を見て',
    '確認[ページ](https://test.org)完了',
    '参照[ドキュメント](https://docs.example.com)してください',
    '[公式サイト](https://official.com)を確認',
    'ダウンロード[ファイル](https://cdn.example.com/file.zip)から',
    '[ヘルプ](https://help.example.com)を読んで',
    '情報[詳細](https://info.example.com)を参照',
    '[ブログ](https://blog.example.com)を見て',
    'これは[テスト](https://example.com)と[サンプル](https://sample.com)です',
    '参照[A](https://a.com)と[B](https://b.com)を確認',
    '[リンク1](https://one.com)と[リンク2](https://two.com)を見て',
    '詳細[ページA](https://a.example.com)および[ページB](https://b.example.com)を参照',
    '[公式](https://official.com)と[非公式](https://unofficial.com)を比較',

    // === Symbol boundary (no check needed) ===
    '（test）',
    '「hello world」',
    'テスト、abc、テスト',
    'テスト。abc。テスト',
    'テスト（abc）です',
    '日本語「hello」テスト',
    '確認（word）完了',
    '開始「phrase here」終了',
    '値：123：確認',
    '項目；abc；完了',
    'テスト！abc！確認',
    '質問？word？回答',
    '（hello world）',
    '「test case」',
    '『example』',
    '【sample】',
    '〈test〉',
    '《example》',
    '〔sample〕',
    '［test］',
    '｛example｝',
    '（abc def）',
    '「foo bar」',
    '『hello world』',
    '【test case】',

    // === Full-width only ===
    'これはテストです',
    'あいうえお',
    '漢字ひらがなカタカナ',
    '日本語のみ',
    'テスト確認完了',
    '開始処理終了',
    '設定変更保存',
    '入力確認出力',
    '読込処理書込',
    '検索結果表示',

    // === Half-width only ===
    'hello world',
    'test123',
    'foo bar baz',
    'abc def ghi',
    'test case example',
    'hello world test',
    'foo bar baz qux',
    'one two three four',
    'alpha beta gamma',
    'first second third',

    // === Mixed with symbols at boundaries ===
    '（test）確認',
    '確認（test）',
    '「word」テスト',
    'テスト「word」',
    '、abc、',
    '。xyz。',
    '！test！',
    '？word？',
    '：abc：',
    '；xyz；',

    // === Edge cases ===
    'a',
    'あ',
    '1',
    'ab',
    'あい',
    '12',
    'abc',
    'あいう',
    '123',
    'テストa確認',
    '確認1完了',
    'あa',
    'aあ',
    '1あ',
    'あ1',

    // === Long vowel mark (ー) is NOT a symbol ===
    'サーバーtestクライアント',
    'データーword処理',
    'コンピューターabc機器',
    'プレイヤーxyz再生',
    'メモリー123容量',
    'バッファーtest確認',
    'パラメーターword設定',
    'カウンターabc値',
    'ポインターxyz参照',
    'レジスターtest登録',
    'サーバー hello world クライアント',
    'データー foo bar 処理',
    'コンピューター abc def 機器',
  ],
  invalid: [
    // === Single word with space (incorrect - should not have space) ===
    {text: 'これは test です', errors: [{}, {}]},
    {text: '日本語 word テスト', errors: [{}, {}]},
    {text: 'あいう abc 漢字', errors: [{}, {}]},
    {text: 'テスト word 確認', errors: [{}, {}]},
    {text: '漢字 abc 平仮名', errors: [{}, {}]},
    {text: 'カタカナ xyz 日本語', errors: [{}, {}]},
    {text: '文字列 abc123 テスト', errors: [{}, {}]},
    {text: 'あ a い', errors: [{}, {}]},
    {text: '漢 x 字', errors: [{}, {}]},
    {text: 'カ a タ', errors: [{}, {}]},
    {text: '日本語 test 日本語', errors: [{}, {}]},
    {text: 'ひらがな word 漢字', errors: [{}, {}]},
    {text: 'カタカナ abc 平仮名', errors: [{}, {}]},
    {text: '混合 test 文字', errors: [{}, {}]},
    {text: '確認 word 完了', errors: [{}, {}]},
    {text: '開始 abc 終了', errors: [{}, {}]},
    {text: '前 word 後', errors: [{}, {}]},
    {text: '上 abc 下', errors: [{}, {}]},
    {text: '左 xyz 右', errors: [{}, {}]},
    {text: '内 test 外', errors: [{}, {}]},

    // === Single word with space before only ===
    {text: 'これは testです', errors: [{}]},
    {text: '日本語 wordテスト', errors: [{}]},
    {text: 'あいう abc漢字', errors: [{}]},
    {text: 'テスト word確認', errors: [{}]},
    {text: '漢字 abc平仮名', errors: [{}]},
    {text: 'カタカナ xyz日本語', errors: [{}]},
    {text: '文字列 abc123テスト', errors: [{}]},
    {text: '日本語 test日本語', errors: [{}]},
    {text: 'ひらがな word漢字', errors: [{}]},
    {text: 'カタカナ abc平仮名', errors: [{}]},

    // === Single word with space after only ===
    {text: 'これはtest です', errors: [{}]},
    {text: '日本語word テスト', errors: [{}]},
    {text: 'あいうabc 漢字', errors: [{}]},
    {text: 'テストword 確認', errors: [{}]},
    {text: '漢字abc 平仮名', errors: [{}]},
    {text: 'カタカナxyz 日本語', errors: [{}]},
    {text: '文字列abc123 テスト', errors: [{}]},
    {text: '日本語test 日本語', errors: [{}]},
    {text: 'ひらがなword 漢字', errors: [{}]},
    {text: 'カタカナabc 平仮名', errors: [{}]},

    // === Numbers with space (incorrect) ===
    {text: 'これは 123 です', errors: [{}, {}]},
    {text: '数字 456 テスト', errors: [{}, {}]},
    {text: '値 789 確認', errors: [{}, {}]},
    {text: 'カウント 100 完了', errors: [{}, {}]},
    {text: '番号 001 登録', errors: [{}, {}]},
    {text: '識別子 999 取得', errors: [{}, {}]},
    {text: 'コード 123456 設定', errors: [{}, {}]},
    {text: '年 2024 月', errors: [{}, {}]},
    {text: '第 1 回', errors: [{}, {}]},
    {text: '全 10 件', errors: [{}, {}]},

    // === Phrase without space (incorrect - should have space) ===
    {text: 'これはhello worldです', errors: [{}, {}]},
    {text: '日本語foo barテスト', errors: [{}, {}]},
    {text: 'あいうabc def漢字', errors: [{}, {}]},
    {text: 'テストhello world確認', errors: [{}, {}]},
    {text: '漢字foo bar平仮名', errors: [{}, {}]},
    {text: 'カタカナabc xyz日本語', errors: [{}, {}]},
    {text: '文字列test caseテスト', errors: [{}, {}]},
    {text: '開始start end終了', errors: [{}, {}]},
    {text: '前before after後', errors: [{}, {}]},
    {text: '上top bottom下', errors: [{}, {}]},
    {text: '左left right右', errors: [{}, {}]},
    {text: '内inner outer外', errors: [{}, {}]},
    {text: '日本語hello world test日本語', errors: [{}, {}]},
    {text: 'ひらがなfoo bar baz漢字', errors: [{}, {}]},
    {text: 'カタカナabc def ghi平仮名', errors: [{}, {}]},
    {text: '混合test case example文字', errors: [{}, {}]},
    {text: '確認check verify完了', errors: [{}, {}]},
    {text: '開始begin start終了', errors: [{}, {}]},
    {text: '設定config setting完了', errors: [{}, {}]},
    {text: '処理process handle終了', errors: [{}, {}]},

    // === Phrase with space before only (missing trailing) ===
    {text: 'これは hello worldです', errors: [{}]},
    {text: '日本語 foo barテスト', errors: [{}]},
    {text: 'あいう abc def漢字', errors: [{}]},
    {text: 'テスト hello world確認', errors: [{}]},
    {text: '漢字 foo bar平仮名', errors: [{}]},
    {text: 'カタカナ abc xyz日本語', errors: [{}]},
    {text: '文字列 test caseテスト', errors: [{}]},
    {text: '開始 start end終了', errors: [{}]},
    {text: '前 before after後', errors: [{}]},
    {text: '上 top bottom下', errors: [{}]},

    // === Phrase with space after only (missing leading) ===
    {text: 'これはhello world です', errors: [{}]},
    {text: '日本語foo bar テスト', errors: [{}]},
    {text: 'あいうabc def 漢字', errors: [{}]},
    {text: 'テストhello world 確認', errors: [{}]},
    {text: '漢字foo bar 平仮名', errors: [{}]},
    {text: 'カタカナabc xyz 日本語', errors: [{}]},
    {text: '文字列test case テスト', errors: [{}]},
    {text: '開始start end 終了', errors: [{}]},
    {text: '前before after 後', errors: [{}]},
    {text: '上top bottom 下', errors: [{}]},

    // === URL without space before (incorrect) ===
    {text: '詳細はhttps://example.com を参照', errors: [{}]},
    {text: 'サイトhttps://example.com/path です', errors: [{}]},
    {text: 'リンクhttps://example.com/path?query=1 を見て', errors: [{}]},
    {text: '参照https://test.org/page 確認', errors: [{}]},
    {text: 'アクセスhttps://sample.net/api してください', errors: [{}]},
    {text: 'ドキュメントhttps://docs.example.com/guide を読んで', errors: [{}]},
    {text: 'ソースhttps://github.com/user/repo を確認', errors: [{}]},
    {text: 'ダウンロードhttps://cdn.example.com/file.zip から取得', errors: [{}]},
    {text: '情報https://info.example.com/news を参照', errors: [{}]},
    {text: 'ヘルプhttps://help.example.com/faq を見て', errors: [{}]},

    // === URL without space after (incorrect) ===
    {text: '詳細は https://example.comを参照', errors: [{}]},
    {text: 'サイト https://example.com/pathです', errors: [{}]},
    {text: 'リンク https://example.com/path?query=1を見て', errors: [{}]},
    {text: '参照 https://test.org/page確認', errors: [{}]},
    {text: 'アクセス https://sample.net/apiしてください', errors: [{}]},
    {text: 'ドキュメント https://docs.example.com/guideを読んで', errors: [{}]},
    {text: 'ソース https://github.com/user/repoを確認', errors: [{}]},
    {text: 'ダウンロード https://cdn.example.com/file.zipから取得', errors: [{}]},
    {text: '情報 https://info.example.com/newsを参照', errors: [{}]},
    {text: 'ヘルプ https://help.example.com/faqを見て', errors: [{}]},

    // === URL without space both sides (incorrect) ===
    {text: '詳細はhttps://example.comを参照', errors: [{}, {}]},
    {text: 'サイトhttps://example.com/pathです', errors: [{}, {}]},
    {text: 'リンクhttps://example.com/path?query=1を見て', errors: [{}, {}]},
    {text: '参照https://test.org/page確認', errors: [{}, {}]},
    {text: 'アクセスhttps://sample.net/apiしてください', errors: [{}, {}]},
    {text: 'ドキュメントhttps://docs.example.com/guideを読んで', errors: [{}, {}]},
    {text: 'ソースhttps://github.com/user/repoを確認', errors: [{}, {}]},
    {text: 'ダウンロードhttps://cdn.example.com/file.zipから取得', errors: [{}, {}]},
    {text: '情報https://info.example.com/newsを参照', errors: [{}, {}]},
    {text: 'ヘルプhttps://help.example.com/faqを見て', errors: [{}, {}]},

    // === Email without space before (incorrect) ===
    {text: 'メアドはfoo@example.com です', errors: [{}]},
    {text: '連絡先test@example.co.jp まで', errors: [{}]},
    {text: '問い合わせinfo@sample.org へ', errors: [{}]},
    {text: 'サポートsupport@help.net まで', errors: [{}]},
    {text: '担当者admin@company.com に連絡', errors: [{}]},
    {text: '送信先mail@domain.io です', errors: [{}]},
    {text: '返信reply@service.com まで', errors: [{}]},
    {text: '登録register@site.net へ', errors: [{}]},
    {text: '通知notify@alert.org に設定', errors: [{}]},
    {text: '確認confirm@verify.com まで', errors: [{}]},

    // === Email without space after (incorrect) ===
    {text: 'メアドは foo@example.comです', errors: [{}]},
    {text: '連絡先 test@example.co.jpまで', errors: [{}]},
    {text: '問い合わせ info@sample.orgへ', errors: [{}]},
    {text: 'サポート support@help.netまで', errors: [{}]},
    {text: '担当者 admin@company.comに連絡', errors: [{}]},
    {text: '送信先 mail@domain.ioです', errors: [{}]},
    {text: '返信 reply@service.comまで', errors: [{}]},
    {text: '登録 register@site.netへ', errors: [{}]},
    {text: '通知 notify@alert.orgに設定', errors: [{}]},
    {text: '確認 confirm@verify.comまで', errors: [{}]},

    // === Email without space both sides (incorrect) ===
    {text: 'メアドはfoo@example.comです', errors: [{}, {}]},
    {text: '連絡先test@example.co.jpまで', errors: [{}, {}]},
    {text: '問い合わせinfo@sample.orgへ', errors: [{}, {}]},
    {text: 'サポートsupport@help.netまで', errors: [{}, {}]},
    {text: '担当者admin@company.comに連絡', errors: [{}, {}]},
    {text: '送信先mail@domain.ioです', errors: [{}, {}]},
    {text: '返信reply@service.comまで', errors: [{}, {}]},
    {text: '登録register@site.netへ', errors: [{}, {}]},
    {text: '通知notify@alert.orgに設定', errors: [{}, {}]},
    {text: '確認confirm@verify.comまで', errors: [{}, {}]},

    // === Long vowel mark (ー) is NOT a symbol - single word with space ===
    {text: 'サーバー test クライアント', errors: [{}, {}]},
    {text: 'データー word 処理', errors: [{}, {}]},
    {text: 'コンピューター abc 機器', errors: [{}, {}]},
    {text: 'プレイヤー xyz 再生', errors: [{}, {}]},
    {text: 'メモリー 123 容量', errors: [{}, {}]},
    {text: 'バッファー test 確認', errors: [{}, {}]},
    {text: 'パラメーター word 設定', errors: [{}, {}]},
    {text: 'カウンター abc 値', errors: [{}, {}]},
    {text: 'ポインター xyz 参照', errors: [{}, {}]},
    {text: 'レジスター test 登録', errors: [{}, {}]},

    // === Long vowel mark (ー) - phrase without space ===
    {text: 'サーバーhello worldクライアント', errors: [{}, {}]},
    {text: 'データーfoo bar処理', errors: [{}, {}]},
    {text: 'コンピューターabc def機器', errors: [{}, {}]},
    {text: 'プレイヤーtest case再生', errors: [{}, {}]},
    {text: 'メモリーhello world容量', errors: [{}, {}]},
  ],
});
